import logo from "../assets/truefit_logo.svg";
import { APP_NAME } from "../config";
import { scoreFromText, scoreTone } from "../utils/score";

function ReportSection({ title, text }) {
  return (
    <section className="mb-9 break-inside-avoid">
      <h2 className="mb-3 border-b border-line pb-2 text-[11px] font-bold uppercase tracking-[.14em] text-ink-500">
        {title}
      </h2>
      <div className="whitespace-pre-wrap text-[13.5px] leading-7 text-ink-700">
        {text || "No result returned."}
      </div>
    </section>
  );
}

function ExportReportPage({ analysis }) {
  if (!analysis) {
    return (
      <div className="grid min-h-screen place-items-center bg-canvas p-6">
        <div className="max-w-md rounded-2xl border border-line bg-white px-6 py-12 text-center shadow-card">
          <span className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-brand-50 text-brand-600">
            <span className="material-symbols-outlined text-[28px]">picture_as_pdf</span>
          </span>
          <h1 className="mt-5 text-2xl font-extrabold tracking-tight">No report to export</h1>
          <p className="mt-2 text-ink-500">Run a resume analysis first, then export its real results.</p>
          <a
            href="#dashboard"
            className="mt-6 inline-flex items-center gap-2 rounded-xl bg-gradient-to-br from-brand-500 to-brand-700 px-6 py-3 text-sm font-semibold text-white shadow-brand transition hover:brightness-110"
          >
            <span className="material-symbols-outlined text-[20px]">bolt</span>
            Analyze Resume
          </a>
        </div>
      </div>
    );
  }

  const score = scoreFromText(analysis.match_analysis);
  const { color: scoreColor, label: scoreLabel } = scoreTone(score);

  return (
    <div className="min-h-screen bg-canvas">
      <header className="print:hidden fixed top-0 z-50 flex h-16 w-full items-center justify-between border-b border-line bg-white/85 px-5 backdrop-blur-md md:px-10">
        <a href="#recent-matches" className="inline-flex items-center gap-1.5 text-sm font-semibold text-ink-700 transition hover:text-brand-600">
          <span className="material-symbols-outlined text-[20px]">arrow_back</span>
          Back to report
        </a>
        <button
          onClick={() => window.print()}
          className="inline-flex items-center gap-2 rounded-xl bg-gradient-to-br from-brand-500 to-brand-700 px-5 py-2.5 text-sm font-semibold text-white shadow-brand transition hover:brightness-110"
        >
          <span className="material-symbols-outlined text-[20px]">download</span>
          Download PDF
        </button>
      </header>

      <main className="flex justify-center px-4 pb-14 pt-24 md:px-10 print:p-0">
        <article className="w-full max-w-[850px] rounded-2xl border border-line bg-white p-8 shadow-lift md:p-14 print:rounded-none print:border-0 print:shadow-none">

          <header className="mb-9 flex items-start justify-between gap-6 border-b border-line pb-7">
            <div className="min-w-0">
              <img src={logo} alt={APP_NAME} className="mb-6 h-auto w-44 object-contain" />
              <h1 className="text-2xl font-extrabold tracking-tight text-ink md:text-3xl">
                {analysis.jobRole || "Resume Match Report"}
              </h1>
              <p className="mt-2 text-sm text-ink-500">
                {analysis.companyName ? `${analysis.companyName} · ` : ""}
                {analysis.resumeName}
              </p>
              <p className="mt-1 text-sm text-ink-400">Generated {analysis.createdAt}</p>
            </div>

            <div className="shrink-0 text-center">
              <div
                className="grid h-24 w-24 place-items-center rounded-full border-[6px]"
                style={{ borderColor: scoreColor, color: scoreColor }}
              >
                <span className="text-2xl font-extrabold">{score}%</span>
              </div>
              <p className="mt-2 text-[11px] font-bold uppercase tracking-wider" style={{ color: scoreColor }}>
                {scoreLabel}
              </p>
            </div>
          </header>

          <ReportSection title="Match Analysis" text={analysis.match_analysis} />
          <ReportSection title="Skill Gap Analysis" text={analysis.skill_gap_analysis} />
          {analysis.jd_redflags && <ReportSection title="Job Description Notes" text={analysis.jd_redflags} />}
          {(analysis.edited_cover_letter || analysis.cover_letter) && (
            <ReportSection title="Cover Letter" text={analysis.edited_cover_letter || analysis.cover_letter} />
          )}

          <footer className="mt-12 border-t border-line pt-4 text-center text-[11px] text-ink-400">
            Generated by {APP_NAME} from the submitted resume and job description.
          </footer>
        </article>
      </main>
    </div>
  );
}

export default ExportReportPage;
